### ISSUE TITLE
sbt assembly fails with "RuntimeException: deduplicate: different file contents found in" guava-19.0.jar

### ISSUE THREAD

**Issue by jaceklaskowski** [aerospike/aerospark#21]
```
$ sbt 'set test in assembly := {}' assembly
...
[error] 1 error was encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/Users/jacek/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-network-common_2.11/2.1.0/spark-network-common_2.11-2.1.0.jar:META-INF/maven/com.google.guava/guava/pom.xml
/Users/jacek/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:META-INF/maven/com.google.guava/guava/pom.xml
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /Users/jacek/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-network-common_2.11/2.1.0/spark-network-common_2.11-2.1.0.jar:META-INF/maven/com.google.guava/guava/pom.xml
[error] /Users/jacek/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:META-INF/maven/com.google.guava/guava/pom.xml
[error] Total time: 12 s, completed Jun 7, 2017 9:09:29 AM
```

**Comment by mzhangsfly** [comment]
From the exception, you have two copies of guava under folder of:  .coursier and maven .m2. You can try to remove one of them e.g. the copy of .coursier

**Comment by jaceklaskowski** [comment]
Tried and failed. Can you please remove `.ivy2` and `.m2` directories and start your build from scratch?

**Comment by mzhangsfly** [comment]
I removed both from my local environment, still couldn't regenerate the exception.  Can you provide your build.sbt as well as the exception?

**Comment by mzhangsfly** [comment]
are you still having problem with the local build?

**Comment by mzhangsfly** [comment]
close it for now unless more update being provided.

**Comment by jaceklaskowski** [comment]
Confirmed. It does compile fine now. Removed `~/.coursier/cache` directory and `bt 'set test in assembly := {}' assembly` worked fine. Sorry for the false alarm.
